# permissions for end users to view kclruns.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: kclrun-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: kcl-controller
    app.kubernetes.io/part-of: kcl-controller
    app.kubernetes.io/managed-by: kustomize
  name: kclrun-viewer-role
rules:
- apiGroups:
  - krm.kcl.dev.fluxcd
  resources:
  - kclruns
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - krm.kcl.dev.fluxcd
  resources:
  - kclruns/status
  verbs:
  - get
