name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install k3d
      run: |
        curl -s https://raw.githubusercontent.com/rancher/k3d/main/install.sh | bash

    - name: Create k3d cluster
      run: |
        k3d cluster create mycluster --servers 1 --agents 2

    - name: Setup Flux CLI
      uses: fluxcd/flux2/action@main
      with:
        version: 'latest'

    - name: Install source-controller
      run: |
        flux install --namespace=source-system --network-policy=false --components=source-controller

    - name: Test
      run: |
        make test
